services:
  - type: web
    name: fine-tune-data-system
    runtime: python3
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m nltk.downloader punkt stopwords wordnet averaged_perceptron_tagger
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: LOW_MEM_MODE
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"

