[theme]
# Fine-Tune Data System - Render Optimized Theme
primaryColor = "#667eea"
backgroundColor = "#f8f9fa"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
# Render.com optimized server configuration
maxUploadSize = 200
enableCORS = true
enableXsrfProtection = false
port = 8501
address = "0.0.0.0"
headless = true

[browser]
# Browser configuration for production
gatherUsageStats = false

[logger]
# Production logging
level = "warning"
messageFormat = "%(asctime)s [%(levelname)s] %(message)s"

[client]
# Client configuration for production
showErrorDetails = false
toolbarMode = "minimal"

[global]
# Global settings for production
developmentMode = false
showWarningOnDirectExecution = false

