[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 10000

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[client]
caching = true
displayEnabled = true
showErrorDetails = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[global]
developmentMode = false
logLevel = "info"
unitTest = false
suppressDeprecationWarnings = true
showWarningOnDirectExecution = false

[mapbox]
token = ""

[deprecation]
showfileUploaderEncoding = false
showImageFormat = false
showPyplotGlobalUse = false

